[build]
  base = "subdir"
  command = "npm run build"
  publish = "subdir/build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Otimizações de cache
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"